# Generated by Django 4.2.7 on 2023-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('ingredientes', models.CharField(max_length=250, null=True, verbose_name='Ingredientes')),
                ('preparacion', models.CharField(max_length=250, null=True, verbose_name='Preparacion')),
                ('fecha_de_creacion', models.DateField(verbose_name='Fecha de creacion')),
            ],
        ),
    ]
