# Generated by Django 4.2.7 on 2023-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterModelTable(
            name='receta',
            table='receta',
        ),
    ]
