# Generated by Django 4.2.7 on 2023-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_crud', '0002_alter_receta_fecha_de_creacion_alter_receta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_imagenes/', verbose_name='Imagen'),
        ),
    ]
