# Generated by Django 4.2.7 on 2023-12-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_crud', '0003_receta_autor_receta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
